LOAD DATA INFILE './CSV/Actor.csv'
INTO TABLE actors
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE './CSV/Director.csv'
INTO TABLE directors
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE './CSV/Movie_Cast.csv'
INTO TABLE movie_cast
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';

LOAD DATA INFILE './CSV/Movies.csv'
INTO TABLE movies
FIELDS TERMINATED BY ',' 
LINES TERMINATED BY '\n';
